// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

BigInt get remDate => RustLib.instance.api.crateApiCueRemDate();

double get fps => RustLib.instance.api.crateApiCueFps();

Future<List<(String, Metadata, Properties)>> cueReadFile(
        {required String file}) =>
    RustLib.instance.api.crateApiCueCueReadFile(file: file);
