// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cue_read_properties`, `get_metadata_value`, `parse_number_total`

Future<void> initFfmpeg() => RustLib.instance.api.crateApiFfmpegInitFfmpeg();

Future<(Metadata, Properties)> readFile({required String file}) =>
    RustLib.instance.api.crateApiFfmpegReadFile(file: file);
