// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> id3WriteMetadata(
        {required String file, required Metadata metadata}) =>
    RustLib.instance.api
        .crateApiId3Id3WriteMetadata(file: file, metadata: metadata);

Future<void> id3WritePicture({required String file, Uint8List? picture}) =>
    RustLib.instance.api
        .crateApiId3Id3WritePicture(file: file, picture: picture);
