// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_or_create_tag_for_file`

Future<void> loftyWriteMetadata(
        {required String file, required Metadata metadata}) =>
    RustLib.instance.api
        .crateApiLoftyLoftyWriteMetadata(file: file, metadata: metadata);

Future<void> loftyWritePicture({required String file, Uint8List? picture}) =>
    RustLib.instance.api
        .crateApiLoftyLoftyWritePicture(file: file, picture: picture);
