name: flubar
description: "audio helper written in flutter"
publish_to: 'none'

version: 0.2.0+2

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  talker_flutter: ^4.6.6
  get: ^4.6.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fast_immutable_collections: ^11.0.3
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  multi_split_view: ^3.6.0
  material_table_view: ^5.0.1
  window_manager: ^0.4.3
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_settings_ui: ^3.0.1
  super_drag_and_drop: ^0.8.24
  super_clipboard: ^0.8.24
  file_picker: ^8.1.7
  collection: ^1.19.0
  super_context_menu: ^0.8.24
  just_audio: ^0.9.43
  just_audio_media_kit:
    git:
      url: https://github.com/AyaseFile/just_audio_media_kit.git
      ref: 05f3587
  media_kit_libs_linux: ^1.1.3
  media_kit_native_event_loop: ^1.0.9
  ffmpeg_cli: ^0.3.0
  rust_lib_flubar:
    path: rust_builder
  flutter_rust_bridge: 2.7.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  hive: ^2.2.3
  unorm_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  custom_lint:
  riverpod_lint: ^2.6.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true