name: flubar
description: "audio helper written in flutter"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  talker_flutter: ^4.4.0
  get: ^4.6.6
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  multi_split_view: ^3.2.2
  material_table_view: ^5.0.0
  window_manager: ^0.3.9
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_settings_ui: ^3.0.1
  desktop_drop: ^0.4.4
  cross_file: ^0.3.4+1
  file_picker: ^8.0.7
  collection: ^1.18.0
  super_context_menu: ^0.8.18
  just_audio: ^0.9.39
  just_audio_media_kit:
    git:
      url: https://github.com/AyaseFile/just_audio_media_kit.git
      ref: ef26219
  media_kit_libs_linux: ^1.1.3
  media_kit_native_event_loop: ^1.0.8
  ffmpeg_cli: ^0.3.0
  rust_lib_flubar:
    path: rust_builder
  flutter_rust_bridge: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true