name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.27.3
      - name: Run build script
        run: python build.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flubar
          path: flubar.tar.gz