name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.4
      - name: Run build script
        run: python build.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flubar
          path: flubar.tar.gz